In [1]:
#numpy - it is an
""""
it is a library 
it works on array
it converts everything in one type
it does operations on numbers

"""

'"\nit is a library \nit works on array\nit converts everything in one type\nit does operations on numbers\n\n'

In [3]:
import numpy as np
list_1 =[10,2,3,4]
x= np.array(list_1)
print(x.shape)

(4,)


In [2]:
"""broadcasting
a=[1,2,3]
a*3 this will give 3,6,9

"""
import numpy as np
list_2 = [
   [ [1,2,3],
    [4,5,6]]
]
x1= np.array(list_2)
print(x1.shape)
""" 
"""

(1, 2, 3)


' \n'

In [ ]:
"""
indexing and slicing 
indexing
"""
list_2 = [
   [1,2,3],
    [4,5,6]
]
x1= np.array(list_2
x1[0][1]

[5]


np.int64(2)

In [14]:
player =np.array([(12,114),(16,27),(14,233),(12,145),(23,123)])
skills =np.array(['keeper','batsman','boweler','batter','bowler'])

In [18]:
print(player)
skills

[[ 12 114]
 [ 16  27]
 [ 14 233]
 [ 12 145]
 [ 23 123]]


array(['keeper', 'batsman', 'boweler', 'batter', 'bowler'], dtype='<U7')

In [30]:
player[player[:, 1]>75]

array([[ 12, 114],
       [ 14, 233],
       [ 12, 145],
       [ 23, 123]])

In [36]:
"""reshaping

"""
arr=np.array([1,2,3,4,5,6,7,8,9,1])
arr.reshape(5,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 1]])

In [37]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1])

In [41]:
#stacking
arr1 = np.array([1,2,3])
arr2 = np.array([3,4,5])
arr = np.concatenate((arr1,arr2))
arr

array([1, 2, 3, 3, 4, 5])

In [42]:
a=[1,2,3,4]
b=np.array(a)
a1= np.arrange(3)

AttributeError: module 'numpy' has no attribute 'arrange'