In [3]:
"""
mathematical operations

"""
list_1 =[1,2,3]
list_2 = [4,5,6]
import numpy as np

In [4]:
arr1 = np.array(list_1)
arr2 = np.array(list_2)

In [5]:
arr1 + arr2

array([5, 7, 9])

In [6]:
arr1-arr2

array([-3, -3, -3])

In [7]:
arr1/arr2

array([0.25, 0.4 , 0.5 ])

In [9]:
print(np.add(arr1,arr2))

[5 7 9]


In [10]:
#multiplication
print(np.multiply(arr2,arr1))

[ 4 10 18]


In [11]:
print(np.cos(0))

1.0


In [25]:
#case study 
height=[1,2,3,4,5,6,7,8,9,3,4,5,76,8,6,4,2]
weight =[11,22,3,3,44,55,66,78,11,22,33,54,44,66,77,44,66]
len(height)

17

In [26]:
height = np.array(height)
weight = np.array(weight)

In [27]:
print(type(height))


<class 'numpy.ndarray'>


In [28]:
print(height.shape)

(17,)


In [29]:
height1 = height *2.25
print("height =",height1,"\n")
weight1 = weight *0.45
print(weight1)

height = [  2.25   4.5    6.75   9.    11.25  13.5   15.75  18.    20.25   6.75
   9.    11.25 171.    18.    13.5    9.     4.5 ] 

[ 4.95  9.9   1.35  1.35 19.8  24.75 29.7  35.1   4.95  9.9  14.85 24.3
 19.8  29.7  34.65 19.8  29.7 ]


In [34]:
bmi = (weight /(height**2))*10000

In [35]:
bmi

array([1.10000000e+05, 5.50000000e+04, 3.33333333e+03, 1.87500000e+03,
       1.76000000e+04, 1.52777778e+04, 1.34693878e+04, 1.21875000e+04,
       1.35802469e+03, 2.44444444e+04, 2.06250000e+04, 2.16000000e+04,
       7.61772853e+01, 1.03125000e+04, 2.13888889e+04, 2.75000000e+04,
       1.65000000e+05])

In [36]:
#for one dimensional arrays indexing is similar to python 
#obtain the 5th element from the array
bmi[4]

np.float64(17600.0)

In [37]:
bmi[-2]

np.float64(27500.0)

In [39]:
#obtain first five
bmi [:4]

array([110000.        ,  55000.        ,   3333.33333333,   1875.        ])

In [40]:
#OBTAIN THE LAST THREE ELEMENTS FROM THE ARRAY
bmi[-3:]

array([ 21388.88888889,  27500.        , 165000.        ])

In [41]:
bmi[bmi<2400]

array([1875.        , 1358.02469136,   76.17728532])

In [42]:
#count the numbers of elements where bmi value is less than 21
len(bmi[bmi<21])

0

In [ ]:
"""statical parameters"""

In [43]:
bmi.min()

np.float64(76.17728531855956)

In [44]:
bmi.max()

np.float64(165000.0)

In [45]:
bmi.mean()

np.float64(30649.88436330724)

In [47]:
np.median(bmi)

np.float64(17600.0)

In [48]:
#lamda .you dont want like for loop 
x = lambda a,b : a*b
x(5,6)

30